/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wl_android_filltool_MemFillTool */

#ifndef _Included_com_wl_android_filltool_MemFillTool
#define _Included_com_wl_android_filltool_MemFillTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wl_android_filltool_MemFillTool
 * Method:    fillMem
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_wl_android_filltool_MemFillTool_fillMem
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wl_android_filltool_MemFillTool
 * Method:    freeMem
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_wl_android_filltool_MemFillTool_freeMem
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
